### ISSUE TITLE
Link to LD reference

### ISSUE THREAD

**Issue by szhan1000** [zhilizheng/SBayesRC#1]
Dear Zhili,

I am interested in applying this new method in our data. But the link to download LD data does not work. Could you please check?

Thanks,
Shizhong

**Comment by zhilizheng** [comment]
Hi Shizhong (@szhan1000 ),

Thanks for the message.  We had an issue with the shared LD files (corrupted size), I will fix this in 1 or 2 days.  I will keep you posted once fixed. 

Regards,
Zhili

**Comment by zhilizheng** [comment]
Hi Shizhong (@szhan1000 ),

I have updated the LD file in the link.  I failed to find a place that share the large files, hence upload it in the Onedrive first.  The files will be complete soon (still uploading). 

Regards,
Zhili

**Comment by szhan1000** [comment]
Thank you so much Zhili for the update!


Shizhong

________________________________

**Comment by zhilizheng** [comment]
Hi Shizhong (@szhan1000 ),

I have updated the files. Let me know if you find any problems. 

Regards,
Zhili
