### ISSUE TITLE
Error in impGa: C++ exception (unknown reason)

### ISSUE THREAD

**Issue by wjiang-datasci** [zhilizheng/SBayesRC#12]
Hi Zhili, 

I tried to run SBayesRC with my own summary statistics and the Eur_HM3_UKBB LD reference provided by you:
Rscript -e "SBayesRC::impute(mafile='${out_prefix}_tidy.ma', LDdir='$ld_folder', \
                  output='${out_prefix}_imp.ma', log2file=TRUE)"

However, I keep having Error message in impGa. The log message is attached below. I tried to run it on both our cluster equipped with slurm manager (OS: Red Hat Enterprise Linux 8, 8.6) and my own macbook (MacOS: 13.5.1), and I tried to run different versions of SBayesRC (from 1.2 to 2.0, and the developing version). The error message is the same for all attempts.

Could you enlighten me how to solve this problem? 

Best,

Wei
------------------------------
Impute the summary data by LD
252905 SNPs in common between GWAS summary and LD
146895 SNPs set from summary data
106010 SNPs flipped alleles
252905 SNPs are typed SNPs
Start summary imputation...
==========1=========
 Imputing...
Read  error (m)
Error in impGa(info$template, idxBlk, info$type, ma_exist$z, idxtt, m,  :
  c++ exception (unknown reason)
Calls: <Anonymous> -> impGa
Execution halted

**Comment by zhilizheng** [comment]
Hi @wjiang-datasci ,

Thanks for the report and the nice detalis.   I just download everything from the link I shared, setup a new system (RHEL 8.8 and 7.6)  and have tests,  I can't replicate the problem.  From the error log, it looks like your LD file is broken,  could you re-download the LD file and unzip again?   

```
wget https://plot.cnsgenomics.com/SBayesRC/LD/HapMap3/ukbEUR_HM3.zip
unzip ukbEUR_HM3.zip
```

Don't hesitate to let me know if this doesn't solve the problem. 

Regards,
Zhili

**Comment by wjiang-datasci** [comment]
Hi Zhili,

Thank you for your prompt reply. I have tried to download the LD file and unzip again. Still, the same issue happened. Is there  other possible reason contributing to this issue?

Best,

Wei

**Comment by wjiang-datasci** [comment]
Hi Zhili,

Yes, I installed the latest version:
> packageVersion('SBayesRC')
[1] ‘0.2.0’

And I have installed the package again, but still facing the same issue. 

Best,

Wei

**Comment by zhilizheng** [comment]
Hi @wjiang-datasci 

Thanks for the information.  Could you paste the full log here ?  I will look into this right now.  Besides, could you share me the results of
```
lscpu
uname -r
```

Many thanks. 

Regards,
Zhili

**Comment by wjiang-datasci** [comment]
Sure, the log I pasted before is the full log I obtained. I also pasted it below with the results of lscpu and uname. 

****************************
(SBayesRC)[wj@r206u22n12.mccleary SBayesRC]$ cat ~/result/SBayesRC/test_imp.ma.log
Impute the summary data by LD
252905 SNPs in common between GWAS summary and LD
146895 SNPs set from summary data
106010 SNPs flipped alleles
252905 SNPs are typed SNPs
Start summary imputation...
==========1=========
 Imputing...
Read  error (m)
Error in impGa(info$template, idxBlk, info$type, ma_exist$z, idxtt, m,  :
  c++ exception (unknown reason)
Calls: <Anonymous> -> impGa
Execution halted

***************************
lscpu
Architecture:           x86_64
  CPU op-mode(s):       32-bit, 64-bit
  Address sizes:        46 bits physical, 48 bits virtual
  Byte Order:           Little Endian
CPU(s):                 28
  On-line CPU(s) list:  0-27
Vendor ID:              GenuineIntel
  Model name:           Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz
    CPU family:         6
    Model:              79
    Thread(s) per core: 1
    Core(s) per socket: 14
    Socket(s):          2
    Stepping:           1
    BogoMIPS:           3999.78
    Flags:              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pa
                        t pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall
                        nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good
                         nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes6
                        4 monitor ds_cpl smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid
                        dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsa
                        ve avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat
                        _l3 cdp_l3 invpcid_single intel_ppin ssbd ibrs ibpb stibp fsgsba
                        se tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a
                         rdseed adx smap intel_pt xsaveopt cqm_llc cqm_occup_llc cqm_mbm
                        _total cqm_mbm_local dtherm ida arat pln pts md_clear flush_l1d
Caches (sum of all):
  L1d:                  896 KiB (28 instances)
  L1i:                  896 KiB (28 instances)
  L2:                   7 MiB (28 instances)
  L3:                   70 MiB (2 instances)
NUMA:
  NUMA node(s):         2
  NUMA node0 CPU(s):    0-13
  NUMA node1 CPU(s):    14-27
Vulnerabilities:
  Itlb multihit:        KVM: Mitigation: VMX unsupported
  L1tf:                 Mitigation; PTE Inversion
  Mds:                  Vulnerable; SMT disabled
  Meltdown:             Vulnerable
  Mmio stale data:      Vulnerable
  Retbleed:             Not affected
  Spec store bypass:    Vulnerable
  Spectre v1:           Vulnerable: __user pointer sanitization and usercopy barriers on
                        ly; no swapgs barriers
  Spectre v2:           Vulnerable, IBPB: disabled, STIBP: disabled, PBRSB-eIBRS: Not af
                        fected
  Srbds:                Not affected
  Tsx async abort:      Vulnerable

*******************************
uname -r
4.18.0-372.52.1.el8_6.x86_64

Best,

Wei

**Comment by zhilizheng** [comment]
Hi @wjiang-datasci, 

This is a really strange problem.  

Could you try my example:
```
wget https://plot.cnsgenomics.com/SBayesRC/example/test_tidy.ma.gz
gunzip test_tidy.ma.gz
```
use the test_tidy instead your summary data to run the program again. 

If it still have the problem,  any chance for a remote desktop sharing, we could look into the problem together under your visual supervision?  Email zhili.zheng  ( _At _ ) broadinstitute.org if you think it's feasible.   Or I would need your SNP list for a simulation, but I guess, it could be enviromental issue, so would like to explore this first. 

Regards,
Zhili

**Comment by wjiang-datasci** [comment]
Hi Zhili,

I just tried your example, still facing the same issue. I agree this is a very strange issue and should be related with environmental configuration. Since it just raises C++ exception with unknown reason, it's difficult to figure out the potential problem by myself.  Remote sharing from you will be helpful. I will email you for your possible time slot. Thank you so much.

Best,

Wei

**Comment by zhilizheng** [comment]
Thanks Wei for the details.  We find the issue could come from the cluster, so I close the issue.  

BTW,  for future readers,  I find the summary data only contains 200,000 SNPs,  while in HapMap3, we have over 1 Million.   The missingness rate is too large for a good imputation quality (we suggest > 70% SNPs are in the summary data, or to be conservative > 80%).  So, I suggest the readers to generate the LD by the genotype, which is also documented on the site (see generate LD).  

Regards,
Zhili
