### ISSUE TITLE
LD Blocks on Build 38

### ISSUE THREAD

**Issue by alexisregelson** [zhilizheng/SBayesRC#13]
Hi,

I see that the reference LD block file is on build 37. Is there one for build 38? Or do you suggest lifting over our own data to build 37 in order to get LD matrices?

Thank you,
Alexis

**Comment by zhilizheng** [comment]
Hi @alexisregelson ,

I tested lift from build 38 to build 37,  it works fine.  The liftover of defination file from 37 to 38, looks weird,  as the block defination has some overlapping after the liftover.   I'm also working on this,  will share the new defination file once I confirmed no problem. I will keep you updated. 

Regards,
Zhili

**Comment by zhilizheng** [comment]
I'm on parental leave after this, so postoned the work on build 38.  I will close the issue first.  You can either liftover, or define the blocks by some method. 

Regards,
Zhili
