### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by Mahantesh-Biradar** [zhilizheng/SBayesRC#14]
Hi, I'm trying to install SBayesRC but I have the following error, can you please suggest how I can address this?

Error: package or namespace load failed for ‘SBayesRC’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/mahantesh/R/x86_64-slackware-linux-gnu-library/4.3/00LOCK-SBayesRC/00new/SBayesRC/libs/SBayesRC.so':
  /home/mahantesh/R/x86_64-slackware-linux-gnu-library/4.3/00LOCK-SBayesRC/00new/SBayesRC/libs/SBayesRC.so: undefined symbol: ssyrk_
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/mahantesh/R/x86_64-slackware-linux-gnu-library/4.3/SBayesRC’
Warning in install.packages :
  installation of package ‘/tmp/RtmpbUP5Th/downloaded_packages/SBayesRC_0.2.2.tar.gz’ had non-zero exit status
  
  PS: I have already installed the required dependencies

**Comment by zhilizheng** [comment]
Hi @Mahantesh-Biradar 

Sorry for late reply.  I was in parental leave (unluckily also sick...). 

Thanks for the report. 

This usually means your R don't have the proper BLAS system installed.  If you can't contact the system admin to fix this, you can install the R in anaconda yourself.  

Steps:
1. install anaconda (search anaconda install)
2. run: conda install r-base
3. fix the path to point to your new R installed by anaconda (if you were in anaconda enviroment, ignore this step). 

I will generate a new build system that will determine the BLAS system in the next release. 

Let me know if this don't solve your issue.  I can update the docker image version.  

Regards,
Zhili

**Comment by Mahantesh-Biradar** [comment]
Hi Zhili,

No problem and I can totally understand. 

Let me try your suggestions and get back to you. 

Thank you,
Mahan

**Comment by zhilizheng** [comment]
Hi Mahan,

I compiled a container version if your cluster support Docker, Apptainer (formerly Singularity).  The container version will update same as R package.  

The example are shown in the main page. 

Regards,
Zhili

**Comment by zhilizheng** [comment]
Hope you have solved the problem.  I will close the issue now.

**Comment by Mahantesh-Biradar** [comment]
Hi Zhili, thank you very much for looking into this. I'm trying to run the package as below, but I'm getting error like "Error in fread(file.path(ld_folder, "snp.info")) :
  File '/SBayesRC/LD_reference/HapMap3/ukbEUR_HM3/snp.info' does not exist or is non-readable. getwd()=='/home/mahan'
Calls: <Anonymous> -> fread
Execution halted"

I did check the snp.info file and it exists in the expected folder.

**Comment by zhilizheng** [comment]
Hi Mahan,

I believe, the path you input is not correct.  /SBayesRC/LD_reference/HapMap3/, this means the root folder /SBayesRC, not from your current folder.  To verify, could try `ls /SBayesRC/LD_reference/HapMap3/`, it should give you an error.  I guess you need to remove the leading "/". 

Regards,
Zhili

**Comment by Mahantesh-Biradar** [comment]
Hi Zhili, 

Following is the path to reference folder and I can see all the relevant files present in this folder:

/SBayesRC/LD_reference/HapMap3/ukbEUR_HM3

**Comment by zhilizheng** [comment]
Hi Mahan,

Could you try `less /SBayesRC/LD_reference/HapMap3/ukbEUR_HM3/snp.info` in terminal without sudo, or root permissions?  The file permission have issue.  

If it has the contents: run R
```
# run R in terminal first by R
require(data.table)
dt = fread("/SBayesRC/LD_reference/HapMap3/ukbEUR_HM3/snp.info")
dt
```
Let me know the outputs. 

Thanks.
Regards,
Zhili

**Comment by Mahantesh-Biradar** [comment]
Hi Zhili, 

I can see the following:

dt
         Chrom         ID   Index GenPos  PhysPos A1 A2   A1Freq     N Block
      1:     1  rs4970383       0      0   838555  A  C 0.247625 20000     1
      2:     1  rs4475691       1      0   846808  T  C 0.199300 20000     1
      3:     1  rs1806509       2      0   853954  A  C 0.609000 20000     1
      4:     1  rs7537756       3      0   854250  G  A 0.209375 20000     1
      5:     1 rs13302982       4      0   861808  G  A 0.980450 20000     1
     ---
1154518:    22  rs3810648 1154517      0 51175626  G  A 0.061975 20000   591
1154519:    22  rs2285395 1154518      0 51178090  A  G 0.055775 20000   591
1154520:    22 rs13056621 1154519      0 51181759  G  A 0.864250 20000   591
1154521:    22  rs3865766 1154520      0 51186228  T  C 0.448125 20000   591
1154522:    22 rs28729663 1154521      0 51219006  A  G 0.137750 20000   591

**Comment by zhilizheng** [comment]
Hi Mahan,

Thanks.  That's really strange.  Could you try run the command in this R?  (replace the YOUR_summary to yours)
```
SBayesRC::tidy(mafile='YOUR_summary', LDdir='/SBayesRC/LD_reference/HapMap3/ukbEUR_HM3',  output='test_tidy.ma')
```

Regards,
Zhili

**Comment by Mahantesh-Biradar** [comment]
Hi Zhili, 

Please note that I'm trying run the package using following option, because I was unable to install the package in R:

apptainer run docker://zhiliz/sbayesrc --ldm-eigen $ld_folder \
    --gwas-summary $ma_file --impute-summary --out ${out_prefix} --threads $threads

Not sure, if I can still follow the following option?

SBayesRC::tidy(mafile='YOUR_summary', LDdir='/SBayesRC/LD_reference/HapMap3/ukbEUR_HM3',  output='test_tidy.ma')

**Comment by zhilizheng** [comment]
Hi Mahan, 

We are approching to the problem.  Did you mount your partition /SBayesRC?   You also need to fix the permission issue in apptainer follow the apptainer document, by default, apptainer doesn't have the permission to the partition mounted by yourself, especially NFS mounting.   

While the above process is complex, to ease the problem debug, could you copy your files to your home folder (/home/YOURNAME)?   Try to run the same command line as the impute.  Mostly the problem would be solved.

Regards,
Zhili
