### ISSUE TITLE
LD missing

### ISSUE THREAD

**Issue by LisaHemforth** [zhilizheng/SBayesRC#16]
Hi! 

I was wondering if your LD was still available somewhere as I cannot find a resources folder.

**Comment by zhilizheng** [comment]
Hi @LisaHemforth,

Thanks for the report.  We documented it,  I have the direct link to that part below, you can download from the link directly.  The LD is very large, so we can't upload into github. (We also wish we could). 

https://github.com/zhilizheng/SBayesRC?tab=readme-ov-file#resources

Regards,
Zhili

**Comment by LisaHemforth** [comment]
Oh I'm sorry I missed the section. Thank you 

Regads, 
Lisa
