### ISSUE TITLE
Feature request: Output annotation specific SNP beta

### ISSUE THREAD

**Issue by dayamgene** [zhilizheng/SBayesRC#17]
As far as I can tell, the SNP level annotation specific beta is not output by SBayesRC (only the final mean SNP betas are reported as output). Would it be possible to add an option to output this? It would be useful for constructing annotation-specific PRS, and to identify the specific SNPs that contribute to annotation enriched heritability.

**Comment by zhilizheng** [comment]
Hi @dayamgene ,

Thanks for the report.  We provide the hsq enrichment,  functional per-SNP heritability enrichment (* .AnnoPerSnpHsqEnrichment)  per-SNP heritability enrichment for each annotation, averaged value and standard deviation were reported.

If you are interested in the annotation sepcific PRS, just match the SNP weights (*.txt file) with your annotation, and pick up the SNP in your annotation category to construct the the PRS. 

Regards,
Zhili
