### ISSUE TITLE
hsq in par file matches varg

### ISSUE THREAD

**Issue by dayamgene** [zhilizheng/SBayesRC#18]
Is the `hsq` (heritability squared?) reported in the `.par` file correct? Its value matches `varg` (genetic variance?) and I have observed at least one instance where `hsq>1`, e.g.:

```
hsq	4.3474619102478
nnz	16743.01
sigmaSq	0.0252796683367342
ssq	7.83830830335617
vare	2.00864835321903
varg	4.3474619102478
```

**Comment by zhilizheng** [comment]
Hi @dayamgene ,

Thanks for the report.  This value is the heritability.    The large value prompt,  your summary data may be Meta-ed, and some condition could cause this.  The most popular one would be, the sample size (N) was input incorrectly.  Hence, the phenotypic variance is not 1, as the model assumed after standarised by N.    Note:   here the vare is not the residual variance, it's the per-block residual in SBayesRC model, so we could not calculate the hsq by varg / (varg + vare).  

If the N is correct,  other things to check:  the summary data may have problem (effect allele issue?), you can check by [DENTIST](https://www.nature.com/articles/s41467-021-27438-7);  The LD misspecification, the summary data from one population, that is not the population from LD. If we didn't provide the LD for that population, you can generate yourself. 

Anyway, this mostly only affected the hsq value if the only reason is N incorrect, or BETA scale issue,  the PRS weights were still accurate to use from our experience. 

Regards,
Zhili
