### ISSUE TITLE
 it needs the effect allele frequency ?

### ISSUE THREAD

**Issue by akbarzadehms** [zhilizheng/SBayesRC#2]
Dear Zhili, 
In running the package, it seems it needs the effect allele frequency to get the answer properly. Am I right? 
I used a summary statistics file on T2D GWAS from the [DIAGRAM](https://diagram-consortium.org/downloads/DIAMANTE_summary_statistics_download.pdf)[ consortium](https://diagram-consortium.org/downloads/DIAMANTE_summary_statistics_download.pdf). When I run the model with an artificial variable such meta$freq = runif(0,1,length(meta))
, the model correctly answered. But without the freq variable, I have an error: "The summary data is not a valid COJO format."
Attached, please find the logs I thought were needed for you. 

Best wishes, 
Mahdi
[test_run_with_freq1.log](https://github.com/zhilizheng/SBayesRC/files/10506502/test_run_with_freq1.log)
[test_run_with_freq2.log](https://github.com/zhilizheng/SBayesRC/files/10506503/test_run_with_freq2.log)
[test_run_without_freq.log](https://github.com/zhilizheng/SBayesRC/files/10506504/test_run_without_freq.log)

**Comment by zhilizheng** [comment]
Hi Mahdi,

Thanks for the report.  We only use the allele frequency for the QC purpose.  So, it would be better to provide the allele frequencies from the summary data.  After the QC, we can ensure the quality of the summary data.     If it's not available, and you are quite confident about your summary data, you can fill the allele frequency from the our LD reference (snp.info located in the downloaded LD, column A1Freq, pay attention to the alleles).  We don't recommend to fill with random value, as our QC pipeline would filter some SNPs out from a wrong criteria.  

I find you only run the prediction in 100 SNPs.  We suggest to run in genome wide. From my experience, the imputation could be good if less 40% of SNPs were missing from the LD reference (to be conservative, 20 - 30% would be good). 

You can use our full pipeline from the demo code in the manual (https://github.com/zhilizheng/SBayesRC#example-code). It would run the QC and imputation automatically.   The summary data should be provided in COJO format (strigent check in the program), columns are: 
```
SNP A1 A2 freq b se p N 
rs1001 A G 0.8493 0.0024 0.0055 0.6653 129850 
rs1002 C G 0.0306 0.0034 0.0115 0.7659 129799 
rs1003 A C 0.5128 0.0045 0.0038 0.2319 129830
...
```

I hope this addressed your question well. 

Regards,
Zhili
