### ISSUE TITLE
Posterior samples for variants?

### ISSUE THREAD

**Issue by cafletezbrant** [zhilizheng/SBayesRC#21]
Thank you for releasing this cool software. Is there a way to get the posterior samples for each variant's beta? This was alluded to in a [previous issue](https://github.com/zhilizheng/SBayesRC/issues/17) but I didn't see it directly addressed, so thought I'd ask.

Best,
Kipper

**Comment by zhilizheng** [comment]
Hi @cafletezbrant ,

Sorry, I assume you were only interested in the categorised hsq which I mentioned in the original post.  I will add this flag,  this will happen in next few weeks. 

Regards,
Zhili

**Comment by zhilizheng** [comment]
Hi @cafletezbrant,

I find I implemented this.   SBayesRC::sbayesrc(…, bOutBeta=TRUE).  

Type ?SBayesRC::sbayesrc to read full doc.

BR,
Zhili
