### ISSUE TITLE
resource is no longer available

### ISSUE THREAD

**Issue by harryyiheyang** [zhilizheng/SBayesRC#23]
Dear Zheng,
It seems that the LD reference panel and the annotation are not available now.
Could you please check it?
wget https://plot.cnsgenomics.com/SBayesRC/Annotation/annot_baseline2.2.zip
--2024-04-21 10:44:19--  https://plot.cnsgenomics.com/SBayesRC/Annotation/annot_baseline2.2.zip
Resolving plot.cnsgenomics.com (plot.cnsgenomics.com)... 203.101.225.58
Connecting to plot.cnsgenomics.com (plot.cnsgenomics.com)|203.101.225.58|:443...

**Comment by zhilizheng** [comment]
Hi @harryyiheyang,

Thanks for the report.  Our server is out of work due a resource issue.  We are contacting our provider. 

You can access the backup link for now: https://drive.google.com/drive/folders/1uxnxDjRJPzo0dTpFnERS5N2NGZX5S-sU?usp=drive_link

Regards,
Zhili

**Comment by zhilizheng** [comment]
I have updated our README page.  Thanks for the report.
