### ISSUE TITLE
More Tthan 30% of SNPs Were Missing After QC

### ISSUE THREAD

**Issue by 1667857557** [zhilizheng/SBayesRC#25]
Dear Dr.Zhang,

Thank you for your excellent work. We encountered some issues while running SBayesRC with the provided workflow and our GWAS summary data. We received a warning that more than 30% of the SNPs were missing after quality control (QC). Could this issue be related to our conversion of GWAS summary frequencies to minor allele frequency (MAF) and the subsequent exclusion of SNPs with MAF < 0.01, considering that MAF was used as frequency in our GCTA-COJO types file? If so, are there any methods we can use to avoid this problem? Thank you in advance!

Best,
Yu-Feng Huang

**Comment by zhilizheng** [comment]
Hi YuFeng,

Thanks for the reports.  It doesn't matter for the MAF cutoff.  

1. SNP name difference.  You can match the SNPs by yourself to the file "snp.info" in our LD folder.  It could be the SNP name  difference.  If this is the case, rename you SNP column to ours by CHR and position.

2. Indeed there were large number of SNPs missing.  If is not case 1,  generate the LD yourself by a refernce genotype file. See https://github.com/zhilizheng/SBayesRC?tab=readme-ov-file#generate-ld

Regards,
Zhili

**Comment by zhilizheng** [comment]
Hi @harryyiheyang ,

You are right.  The QC steps are for orginal scale data, which is the most common case.   The rate2pq is for some summary statistics error, which the depends on the sample size and phenotypic variance.   I will revise the document, if the summary statistics are from standardzied scale, the QC steps need to be done manually.  I will improve this part in the future.  

Thanks.

Regards,
Zhili

**Comment by zhilizheng** [comment]
Hi @harryyiheyang ,

I have fixed the document.  Thanks for the report. 

Regards,
Zhili

**Comment by harryyiheyang** [comment]
Hi @zhilizheng 
Thank you for your immediate response. We performed meta-analysis using METAL for multiple traits using the public GWAS summary data and the MVP GWAS data, where the "scheme samplesize" option was chosen. The main reason we selected "scheme samplesize" is that the effect sizes in different cohorts can be of different scales, making it a safer approach to perform meta-analysis using sample sizes. The output only contains the Z-score and other information and hence we generated the COJO file with the way aforementioned. Could you please provide us with guidance on how to proceed in this case?
Thank you very much.

**Comment by zhilizheng** [comment]
Hi @harryyiheyang, 

Sorry for the late reply, I was overwhelmed last week.    The work around could be: convert the the standarised scale back to it's original scale. You can try to recover its scale by (workable R code): 

b = b_YOUR_side / sqrt( 2 * freq * (1 - freq)) 
se = se_YOUR_side / sqrt( 2 * freq * (1 - freq)) 

The freq is the allele frequency for each SNP.   Then use this new b and se to replace in the COJO for analysis.   

Let me know how it goes. 

Regards,
Zhili

**Comment by harryyiheyang** [comment]
@zhilizheng 
Thank you very much for your answer. It helps a lot!
Yihe
