### ISSUE TITLE
LD format

### ISSUE THREAD

**Issue by LisaHemforth** [zhilizheng/SBayesRC#27]
Hello, 

I am trying to use SBayesRC with my own LD data. As the provided LD data is made of a couple hundred binary files I am unsure of the necessary structure of this data. Could you tell me how you generated these files? 

All the best.

**Comment by zhilizheng** [comment]
Hi @LisaHemforth ,

You don't need to understand the formats.  There are two ways:  
1. Running the SBayesRC R package directly:  https://github.com/zhilizheng/SBayesRC?tab=readme-ov-file#generate-ld
2. Container version, see the command line document. apptainer run docker://zhiliz/sbayesrc:0.2.5

Regards,
Zhili

**Comment by LisaHemforth** [comment]
Hi, 

Thank you so much for your answer. I am experiencing an issue with one of my bins generated by step one and then processed by gctb. When I try doing step 3 I get an error saying that I get an overflow when trying to perform nmarker*nmarker. Indeed this bin has over 47,000 markers. Is there any way to increase the number of bins to split this one further? Will this not pose an issue later on in the analysis? 

Thank you in advance for your help
Regards, 

Lisa

**Comment by zhilizheng** [comment]
Hi @LisaHemforth ,

It's best to use the block as the whole, however, if it's out of resource, you can customized the block. The difference of prediction accuracy is usually minor (causal may not in that boundary)

Steps (I didn't test this, so hope it can work): 
1. download: https://github.com/zhilizheng/SBayesRC/blob/main/inst/extdata/ref4cM_v37.pos
2. seperate the big ones. 
3. Put the seperated one to the end of the file (Block +1). Then, you don't need to change the Block number, and the LD you genearetd can be reused. 
4. Run step1 to 4 with the new position defination file. 

Let me know how it goes. 

Regards,
Zhili

**Comment by zhilizheng** [comment]
I added another function (readEig) to read the eigen matrix if you are interested.  So the users don't need to know the formats. 

Regards,
Zhili
