### ISSUE TITLE
Error in computing weights

### ISSUE THREAD

**Issue by SoleilChenxu** [zhilizheng/SBayesRC#28]
Hi there,

 I reveived the error below in computing the weights step. Do you have idea why this happended? 
_"Running SBayesRC with annotation
Annotation column 2 has too small XPX: 0, please remove this column from annotation data or perform re-scale. terminate called after throwing an instance of 'char const_*"

The format of my annotation file is:

SNP Intercept Coding Conserved CTCF
rs539032812     1       0       0       0
rs12238997      1       0       0       0
rs371890604     1       0       0       0
rs200531508     1       0       0       0

Thanks!

**Comment by zhilizheng** [comment]
Hi @SoleilChenxu,

Thanks for the reports.  Could you check the "Coding" contains just one value after the SNP merging?   The problem will usually be raised when the annotation only has single value after matching with the LD pannel.  

Regards,
Zhili

**Comment by phycochow** [comment]
Hi @zhilizheng, we are encountering the same error message. In our case, that would be 'Male_increased_heart_weight'? Could you show us where we can find the 'SNP merging' step please? Thank you

SNP     Intercept       Male_increased_heart_weight     Female_increased_heart_weight

**Comment by SoleilChenxu** [comment]
> Hi @SoleilChenxu,
> 
> Thanks for the reports. Could you check the "Coding" contains just one value after the SNP merging? The problem will usually be raised when the annotation only has single value after matching with the LD pannel.
> 
> Regards, Zhili

Hi Zhili, thank you for your reply. I just adjusted the format of annotation file, from txt file to tab-delimited file. It works now.

Best, Chenxu

**Comment by zhilizheng** [comment]
Hi @phycochow ,

You can merge your summary data with the ld_folder/snp.info. Sometimes, the annotation only contains single value when in subset of the SNPs.  

Also as mentioned by @SoleilChenxu ,  the format sometimes matters.  Although this looks strange to me.  It could be possible that the anntoation is not recognozied by our program.  The tab-delimited file works best.   I will add the document for this. 

Thanks for your reports. 

Regards,
Zhili
