### ISSUE TITLE
Calc weight: Error in if (rel_max > 1.25) { : missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by bciezah1** [zhilizheng/SBayesRC#29]
Hello there,

I hope this message finds you well. I am writing to you because I am having an error message (bold) I cannot fix it. I have been using your nice package with 3 different cohorts (hispanic, europe and african). It worked pretty well with the european and the hispanic, but not with the african. I simply do not undersstand the error message. Can you help me?

Thank you in advance

This is the command line I used:

**# load library**
module load SBayesRC/0.2.5

**# load variables**
ma_file="./base_AA/ma_file_ready"
ld_folder="./ukbAFR_HM3/"
annot="./annot_baseline2.2.txt"
out_prefix="./base_AA/myoutput"
threads=1

**# step1**
 singularity exec /mnt/mfs/cluster/bin/SBayesRC/sbayesrc.sif sbayesrc --ldm-eigen $ld_folder --gwas-summary $ma_file --impute-summary --out ${out_prefix} --threads $threads

**#Step 2 → calculate weights**
singularity exec /mnt/mfs/cluster/bin/SBayesRC/sbayesrc.sif sbayesrc --ldm-eigen $ld_folder --gwas-summary ${out_prefix}.imputed.ma --sbayes RC --annot $annot --out ${out_prefix} --threads $threads

**HERE IS THE ISSUE (It works well with the other two cohorts).**

Tune with parameter 0.99
Running SBayesRC without annotation
 Number of variants from LD information: 1131955
Start reading LD information, and cutting the variance to 0.99...
Found LD in ./ukbAFR_HM3//block{BLOCK}.eigen.bin, type: 2
Finish reading 591 LD blocks
 Var_y: 1
 Mean vare: 1
Number of distributions: 5
Set beta cutoff threshold: 0.00459192
Start MCMC with 150 iterations...
  Iter 100, nnz=8045, sigmaSq=0.000, hsq=0.000, ssq=0.000, n2=5131, n3=2439, n4=470, n5=5, vg2=0.061, vg3=0.290, vg4=0.593, vg5=0.053,  vare=1.000, rmVariants=0, flipSign=0, time=52.326

Tune with parameter 0.95
Running SBayesRC without annotation
 Number of variants from LD information: 1131955
Start reading LD information, and cutting the variance to 0.95...
Found LD in ./ukbAFR_HM3//block{BLOCK}.eigen.bin, type: 2
Finish reading 591 LD blocks
 Var_y: 1
 Mean vare: 1
Number of distributions: 5
Set beta cutoff threshold: 0.00459192
Start MCMC with 150 iterations...
  Iter 100, nnz=6963, sigmaSq=0.000, hsq=0.000, ssq=0.000, n2=5264, n3=1618, n4=25, n5=56, vg2=0.076, vg3=0.252, vg4=0.028, vg5=0.642,  vare=1.000, rmVariants=0, flipSign=0, time=38.415

Tune with parameter 0.9
Running SBayesRC without annotation
 Number of variants from LD information: 1131955
Start reading LD information, and cutting the variance to 0.9...
Found LD in ./ukbAFR_HM3//block{BLOCK}.eigen.bin, type: 2
Finish reading 591 LD blocks
 Var_y: 1
 Mean vare: 1
Number of distributions: 5
Set beta cutoff threshold: 0.00459192
Start MCMC with 150 iterations...
  Iter 100, nnz=8725, sigmaSq=0.000, hsq=0.000, ssq=0.000, n2=5624, n3=2415, n4=625, n5=61, vg2=0.043, vg3=0.170, vg4=0.458, vg5=0.327,  vare=1.000, rmVariants=0, flipSign=0, time=31.120
**Tuning Done
Error in if (rel_max > 1.25) { : missing value where TRUE/FALSE needed
Calls: <Anonymous>
Execution halted**

**Comment by zhilizheng** [comment]
Hi @bciezah1 ,

Thanks for the reports. 

Could you check the \${out_prefix}.imputed.ma, if there are some NA values there?   If this is the case, just manually set the b to 0, and se to the mean value of se, and N to the median value of N.   It could result from some blocks have no SNPs at all, hence the imputation failed with NA values.   

Let me know if this sovles the problem. I will imrove the code in next release.  Thanks. 

Regards,
Zhili

**Comment by bciezah1** [comment]
It worked, thanks!!
