### ISSUE TITLE
effect allele frequency is missing in summary statistics

### ISSUE THREAD

**Issue by SoleilChenxu** [zhilizheng/SBayesRC#32]
Hi Zhili,

Thank you for your excellent work. I am applying the method in my analysis. I have got a question maybe you could give the suggestion. 

The effect allele frequency is not available in my summary statistics, making it problematic to generate the cojo format file. You have suggested in previous converstion to use the frequency information in _snp.info_ file. However, there are more than 10 million SNPs in my summary statistics. Some of the SNPs are not present in _snp.info_ file. Do you have any advice regarding this? Can I still use the allele frequency in snp.info although the SNPs would be missing? Will this have an influence on the results?

Thanks in advance.

Best, Chenxu

**Comment by zhilizheng** [comment]
HI @SoleilChenxu ,

Yes,  if you are using our LD resources, just keep the same set of SNPs.   The other SNP not in common  will still be removed in the QC steps, hence the allele frequency information is not used for those SNPs. 

Regards,
Zhili

**Comment by SoleilChenxu** [comment]
Hi Zhili,

Briliiant. I see. I do use the provided LD resources. Thank you! 

Best,
Chenxu

**Comment by SoleilChenxu** [comment]
> HI @SoleilChenxu ,
> 
> Yes, if you are using our LD resources, just keep the same set of SNPs. The other SNP not in common will still be removed in the QC steps, hence the allele frequency information is not used for those SNPs.
> 
> Regards, Zhili


Hi Zhili,

Just a quick follow-up question. If I use the allele frequency in the provided resouces. I guess it's also better to use the sample size (N) in _snp.info_ file right? Or I can use the N in the original summary statistics?

Best,
Chenxu

**Comment by zhilizheng** [comment]
Hi @SoleilChenxu ,

No,  you have to use your own per-SNP sample size.   Only the allele frequency can be used from our LD panel, if you are sure your data quality is good. 

Regards,
Zhili

**Comment by SoleilChenxu** [comment]
> Hi @SoleilChenxu ,
> 
> No, you have to use your own per-SNP sample size. Only the allele frequency can be used from our LD panel, if you are sure your data quality is good.
> 
> Regards, Zhili

Hi Zhili,

Okay I see. Thank you very much!

Best,
Chenxu
