### ISSUE TITLE
Error during sbayesrc - c++ exception (unknown reason)

### ISSUE THREAD

**Issue by lkjgoose** [zhilizheng/SBayesRC#35]

**Comment by lkjgoose** [comment]
Hello, I came across this error during sbayesrc and i cannot find any reason.
I runned 
Rscript -e "SBayesRC::sbayesrc(mafile='$ma_file', LDdir='$ld_folder', \
                  outPrefix='$out_prefix', annot='$annot', log2file=TRUE)"
Can I get any ideas why it happened? thank you. 
![sbayes_error](https://github.com/user-attachments/assets/1cc995ca-b5ac-47c5-ac34-6f1498859f86)

**Comment by zhilizheng** [comment]
Hi @lkjgoose ,

Thanks for the feedback. 

You need run all the steps in the tutorial. The SNP set may be inconsistent between the LD and the summary stats.  So, the steps for the clean and impute will be necessary in this case. 

Regards,
Zhili
