### ISSUE TITLE
Error: File '*_tmp.sscore' does not esist or is non-readable

### ISSUE THREAD

**Issue by alisonrocco** [zhilizheng/SBayesRC#37]
Hi, 

I am getting the following error when trying to run SBayesRC::prs()

Error: File 'PRS_Results_ImputedPanel_tmp.sscore' does not exist or is non-readable. 
Execution halted. 

I am left with the following files in my working directory: 
PRS_Results_ImputedPanel_tmp.snplist
PRS_Results_ImputedPanel_tmp.nosex
PRS_Results_ImputedPanel_tmp.profile
PRS_Results_ImputedPanel_tmp.log

There are no errors present in the *_tmp.log file.  This step seems to have completed successfully with high variant retention.

I am running the program using one genotype file containing all chromosomes and setting genoCHR=""

Please let me know if you have any idea what might be causing this error or how to resolve it. 

Sincerely, 
Alison

**Comment by zhilizheng** [comment]
Hi @alisonrocco ,

Thanks for the report, this is because your plink is the plink1.9, not the plink2.0 alpha.   So, you have the *.profile.   Pass the path of plink2 with parameter tool='plink2_YOUR_PATH', or set the plink2 in your path to the plink2 alpha.

Regards,
Zhili

**Comment by alisonrocco** [comment]
Hi @zhilizheng , 

Thank you so much! That resolved the issue
