### ISSUE TITLE
An extra column 'WD' in the LD data is required for impute()

### ISSUE THREAD

**Issue by shinichinamba** [zhilizheng/SBayesRC#4]
Dear Zhili,

I found that `impute()` caused an error because it internally tried to rename the column name of `$LD_PATH/snp.info`, but the length of the new column names (9) did not match the actual length (8). 
This was because the new column names included an extra name, `'WD'`; it seemed that this column was not used in any functions.
I observed this issue when using UKB EAS imputed LD data.

(Although it was not a straightforward solution, I've added a dummy column to $LD_PATH/snp.info and successfully imputed the summary statistics.)

Best,

Shinichi

**Comment by zhilizheng** [comment]
Hi Shinichi,

Thanks for the report and sorry the late reply. 

I'm a bit confused with your description, and failed to replicated the issue in my test data.  Could you figure me the head lines of your summary data to impute?  I will generate an similar case to reproduce. 

Thanks.

Regards,
Zhili

**Comment by zhilizheng** [comment]
Hi Shinichi,

thanks for the report and sorry for the late reply.  I have find the issue in our new LD files in EAS (no genetic distance). 

I will fix the code soon.  for your running, you can add extra column into the $LD_PATH/snp.info file before the BP column. 

Regards,
Zhili

**Comment by zhilizheng** [comment]
Hi Shinichhi,

I have fixed the issue.  Thanks for the report.   Let me know if it has further issues.  

Regards,
Zhili
