### ISSUE TITLE
Downloading LD-matrix via googledrive never works.

### ISSUE THREAD

**Issue by Ararder** [zhilizheng/SBayesRC#5]
Hi,

I've been trying to download the UKB LD-matrix via the google drive link, but It keeps erroring out around 10%.

I've tried downloading manually via both safari and chrome, as well as with https://googledrive.tidyverse.org, and https://github.com/wkentaro/gdown.

Do the download work for you internally? Is the UKB ld-matrix stored elsewhere also?
I would love to apply SbayesRC for our projects!
Best,
Arvid

**Comment by zhilizheng** [comment]
Hi @Ararder 

Thanks for the report.  I downloaded from the link, and find there is no problem on my side after I tried all the big files.  
I will need sometime to upload to another location for you. I will let you know after I finish this. That will be suitable for anyone to download in command line directly. 

Regards,
Zhili

**Comment by zhilizheng** [comment]
Hi @Ararder ,

Sorry that we still haven't got an server to hold those 150GB files.  I have updated the LD files in the resources section.  We will let you know once we get the direct download link. 

We also updated our software.  If you have downloaded the resources,  don't need to re-download again.  We added the LD from AFR. 

Regards,
Zhili

**Comment by zhilizheng** [comment]
Hi @Ararder 

Glad to hear the problem is gone.  I didn't do someing to it.   

I have fixed the link in the document, now the resources can be downloaded by "wget" or "curl" directly in command line.  Beside, we provided an example data. (Refer to the home page, Resources section). 

Let me know if this fix all the issue. 

Regards,
Zhili

**Comment by bciezah1** [comment]
Dear Zhili,

I hope this message find you well. I am sorry if this question is too basic, but can you please share the full 'wget' command to download the data from the drive? I have been trying to download the data (imputed data from the LD folder) using the link you provide in 'resources' without success. I was able to download the HapMap3, but I am having a hard time with the imputed data.

Thank you,

**Comment by zhilizheng** [comment]
Hi @bciezah1 ,

Thanks for the report.  It's not possible to download from the Google drive by "wget". R::googledrive api or, if you prefer a tool, rclone may work.  This is only provided as supplement.   Instead,  we provide the link works for "wget" directly,  Try to copy the link from the hyperlink directly:  https://github.com/zhilizheng/SBayesRC?tab=readme-ov-file#resources

Regards,
Zhili

**Comment by bciezah1** [comment]
THANK you so much for your quick response, it is very appreciated. Yes, now is working by copying the link from the hyperlink you mentioned. In case anyone need this command line to download the imputed euro data, here it is:

**wget https://sbayes.pctgplots.cloud.edu.au/data/SBayesRC/resources/v2.0/LD/Imputed/ukbEUR_Imputed.zip**
