### ISSUE TITLE
problem in installing

### ISSUE THREAD

**Issue by irgp2019** [zhilizheng/SBayesRC#6]
Hi 
sorry but I have problem in installing SBayes in R.
linux x86-64 - Centos7 - R 3.6
I get this error:

* installing *source* package ‘SBayesRC’ ...
** using staged installation
** libs
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG  -I"/usr/lib64/R/library/Rcpp/include" -I"/usr/lib64/R/library/BH/include" -I"/usr/lib64/R/library/RcppEigen/include" -I/usr/local/include -fopenmp -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c AnnoProb.cpp -o AnnoProb.o
AnnoProb.cpp: In member function ‘void AnnoProb::annoEffect_sample_Gibbs(const MatrixXf&)’:
AnnoProb.cpp:197:51: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                 for (unsigned j = 0, idx = 0; j < numSnps; ++j) {
                                                   ^
AnnoProb.cpp:242:38: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             for (unsigned k = 1; k < numAnno; ++k) {
                                      ^
AnnoProb.cpp: In constructor ‘AnnoProb::AnnoProb(std::string, int, const VectorXf&, Eigen::MatrixXf&, bool, double)’:
AnnoProb.cpp:324:63: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if(fread(annoMat.data(), sizeof(float), n_ele, hAnnot) != n_ele){
                                                               ^
In file included from /usr/include/c++/4.8.2/utility:70:0,
                 from /usr/include/c++/4.8.2/unordered_map:38,
                 from /usr/lib64/R/library/Rcpp/include/Rcpp/platform/compiler.h:153,
                 from /usr/lib64/R/library/Rcpp/include/Rcpp/r/headers.h:62,
                 from /usr/lib64/R/library/Rcpp/include/RcppCommon.h:30,
                 from /usr/lib64/R/library/Rcpp/include/Rcpp.h:27,
                 from commR.h:27,
                 from AnnoProb.cpp:12:
/usr/include/c++/4.8.2/bits/stl_pair.h: In instantiation of ‘constexpr std::pair<_T1, _T2>::pair(_U1&&, const _T2&) [with _U1 = const char (&)[13]; <template-parameter-2-2> = void; _T1 = const std::basic_string<char>; _T2 = std::basic_ofstream<char>]’:
/usr/include/c++/4.8.2/bits/stl_tree.h:140:49:   required from ‘std::_Rb_tree_node<_Val>::_Rb_tree_node(_Args&& ...) [with _Args = {const char (&)[13], std::basic_ofstream<char, std::char_traits<char> >}; _Val = std::pair<const std::basic_string<char>, std::basic_ofstream<char> >]’
/usr/include/c++/4.8.2/ext/new_allocator.h:120:4:   required from ‘void __gnu_cxx::new_allocator<_Tp>::construct(_Up*, _Args&& ...) [with _Up = std::_Rb_tree_node<std::pair<const std::basic_string<char>, std::basic_ofstream<char> > >; _Args = {const char (&)[13], std::basic_ofstream<char, std::char_traits<char> >}; _Tp = std::_Rb_tree_node<std::pair<const std::basic_string<char>, std::basic_ofstream<char> > >]’
/usr/include/c++/4.8.2/bits/alloc_traits.h:254:4:   required from ‘static typename std::enable_if<std::allocator_traits<_Alloc>::__construct_helper<_Tp, _Args>::value, void>::type std::allocator_traits<_Alloc>::_S_construct(_Alloc&, _Tp*, _Args&& ...) [with _Tp = std::_Rb_tree_node<std::pair<const std::basic_string<char>, std::basic_ofstream<char> > >; _Args = {const char (&)[13], std::basic_ofstream<char, std::char_traits<char> >}; _Alloc = std::allocator<std::_Rb_tree_node<std::pair<const std::basic_string<char>, std::basic_ofstream<char> > > >; typename std::enable_if<std::allocator_traits<_Alloc>::__construct_helper<_Tp, _Args>::value, void>::type = void]’
/usr/include/c++/4.8.2/bits/alloc_traits.h:393:57:   required from ‘static decltype (_S_construct(__a, __p, (forward<_Args>)(std::allocator_traits::construct::__args)...)) std::allocator_traits<_Alloc>::construct(_Alloc&, _Tp*, _Args&& ...) [with _Tp = std::_Rb_tree_node<std::pair<const std::basic_string<char>, std::basic_ofstream<char> > >; _Args = {const char (&)[13], std::basic_ofstream<char, std::char_traits<char> >}; _Alloc = std::allocator<std::_Rb_tree_node<std::pair<const std::basic_string<char>, std::basic_ofstream<char> > > >; decltype (_S_construct(__a, __p, (forward<_Args>)(std::allocator_traits::construct::__args)...)) = <type error>]’
/usr/include/c++/4.8.2/bits/stl_tree.h:408:36:   required from ‘std::_Rb_tree_node<_Val>* std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_M_create_node(_Args&& ...) [with _Args = {const char (&)[13], std::basic_ofstream<char, std::char_traits<char> >}; _Key = std::basic_string<char>; _Val = std::pair<const std::basic_string<char>, std::basic_ofstream<char> >; _KeyOfValue = std::_Select1st<std::pair<const std::basic_string<char>, std::basic_ofstream<char> > >; _Compare = std::less<std::basic_string<char> >; _Alloc = std::allocator<std::pair<const std::basic_string<char>, std::basic_ofstream<char> > >; std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_Link_type = std::_Rb_tree_node<std::pair<const std::basic_string<char>, std::basic_ofstream<char> > >*]’
/usr/include/c++/4.8.2/bits/stl_tree.h:1622:64:   required from ‘std::pair<std::_Rb_tree_iterator<_Val>, bool> std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_M_emplace_unique(_Args&& ...) [with _Args = {const char (&)[13], std::basic_ofstream<char, std::char_traits<char> >}; _Key = std::basic_string<char>; _Val = std::pair<const std::basic_string<char>, std::basic_ofstream<char> >; _KeyOfValue = std::_Select1st<std::pair<const std::basic_string<char>, std::basic_ofstream<char> > >; _Compare = std::less<std::basic_string<char> >; _Alloc = std::allocator<std::pair<const std::basic_string<char>, std::basic_ofstream<char> > >]’
/usr/include/c++/4.8.2/bits/stl_map.h:541:64:   required from ‘std::pair<typename std::_Rb_tree<_Key, std::pair<const _Key, _Tp>, std::_Select1st<std::pair<const _Key, _Tp> >, _Compare, typename _Alloc::rebind<std::pair<const _Key, _Tp> >::other>::iterator, bool> std::map<_Key, _Tp, _Compare, _Alloc>::emplace(_Args&& ...) [with _Args = {const char (&)[13], std::basic_ofstream<char, std::char_traits<char> >}; _Key = std::basic_string<char>; _Tp = std::basic_ofstream<char>; _Compare = std::less<std::basic_string<char> >; _Alloc = std::allocator<std::pair<const std::basic_string<char>, std::basic_ofstream<char> > >; typename std::_Rb_tree<_Key, std::pair<const _Key, _Tp>, std::_Select1st<std::pair<const _Key, _Tp> >, _Compare, typename _Alloc::rebind<std::pair<const _Key, _Tp> >::other>::iterator = std::_Rb_tree_iterator<std::pair<const std::basic_string<char>, std::basic_ofstream<char> > >]’
AnnoProb.cpp:87:93:   required from here
/usr/include/c++/4.8.2/bits/stl_pair.h:134:45: error: use of deleted function ‘std::basic_ofstream<char>::basic_ofstream(const std::basic_ofstream<char>&)’
  : first(std::forward<_U1>(__x)), second(__y) { }
                                             ^
In file included from /usr/lib64/R/library/RcppEigen/include/unsupported/Eigen/SparseExtra:22:0,
                 from /usr/lib64/R/library/RcppEigen/include/RcppEigenForward.h:40,
                 from /usr/lib64/R/library/RcppEigen/include/RcppEigen.h:25,
                 from commR.h:28,
                 from AnnoProb.cpp:12:
/usr/include/c++/4.8.2/fstream:599:11: note: ‘std::basic_ofstream<char>::basic_ofstream(const std::basic_ofstream<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_ofstream : public basic_ostream<_CharT,_Traits>
           ^
/usr/include/c++/4.8.2/fstream:599:11: error: use of deleted function ‘std::basic_ostream<char>::basic_ostream(const std::basic_ostream<char>&)’
In file included from /usr/include/c++/4.8.2/iterator:64:0,
                 from /usr/lib64/R/library/Rcpp/include/RcppCommon.h:50,
                 from /usr/lib64/R/library/Rcpp/include/Rcpp.h:27,
                 from commR.h:27,
                 from AnnoProb.cpp:12:
/usr/include/c++/4.8.2/ostream:58:11: note: ‘std::basic_ostream<char>::basic_ostream(const std::basic_ostream<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_ostream : virtual public basic_ios<_CharT, _Traits>
           ^
/usr/include/c++/4.8.2/ostream:58:11: error: use of deleted function ‘std::basic_ios<char>::basic_ios(const std::basic_ios<char>&)’
In file included from /usr/include/c++/4.8.2/ios:44:0,
                 from /usr/include/c++/4.8.2/ostream:38,
                 from /usr/include/c++/4.8.2/iterator:64,
                 from /usr/lib64/R/library/Rcpp/include/RcppCommon.h:50,
                 from /usr/lib64/R/library/Rcpp/include/Rcpp.h:27,
                 from commR.h:27,
                 from AnnoProb.cpp:12:
/usr/include/c++/4.8.2/bits/basic_ios.h:66:11: note: ‘std::basic_ios<char>::basic_ios(const std::basic_ios<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_ios : public ios_base
           ^
In file included from /usr/include/c++/4.8.2/ios:42:0,
                 from /usr/include/c++/4.8.2/ostream:38,
                 from /usr/include/c++/4.8.2/iterator:64,
                 from /usr/lib64/R/library/Rcpp/include/RcppCommon.h:50,
                 from /usr/lib64/R/library/Rcpp/include/Rcpp.h:27,
                 from commR.h:27,
                 from AnnoProb.cpp:12:
/usr/include/c++/4.8.2/bits/ios_base.h:786:5: error: ‘std::ios_base::ios_base(const std::ios_base&)’ is private
     ios_base(const ios_base&);
     ^
In file included from /usr/include/c++/4.8.2/ios:44:0,
                 from /usr/include/c++/4.8.2/ostream:38,
                 from /usr/include/c++/4.8.2/iterator:64,
                 from /usr/lib64/R/library/Rcpp/include/RcppCommon.h:50,
                 from /usr/lib64/R/library/Rcpp/include/Rcpp.h:27,
                 from commR.h:27,
                 from AnnoProb.cpp:12:
/usr/include/c++/4.8.2/bits/basic_ios.h:66:11: error: within this context
     class basic_ios : public ios_base
           ^
In file included from /usr/lib64/R/library/RcppEigen/include/unsupported/Eigen/SparseExtra:22:0,
                 from /usr/lib64/R/library/RcppEigen/include/RcppEigenForward.h:40,
                 from /usr/lib64/R/library/RcppEigen/include/RcppEigen.h:25,
                 from commR.h:28,
                 from AnnoProb.cpp:12:
/usr/include/c++/4.8.2/fstream:599:11: error: use of deleted function ‘std::basic_ios<char>::basic_ios(const std::basic_ios<char>&)’
     class basic_ofstream : public basic_ostream<_CharT,_Traits>
           ^
/usr/include/c++/4.8.2/fstream:599:11: error: use of deleted function ‘std::basic_filebuf<char>::basic_filebuf(const std::basic_filebuf<char>&)’
/usr/include/c++/4.8.2/fstream:72:11: note: ‘std::basic_filebuf<char>::basic_filebuf(const std::basic_filebuf<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_filebuf : public basic_streambuf<_CharT, _Traits>
           ^
In file included from /usr/include/c++/4.8.2/ios:43:0,
                 from /usr/include/c++/4.8.2/ostream:38,
                 from /usr/include/c++/4.8.2/iterator:64,
                 from /usr/lib64/R/library/Rcpp/include/RcppCommon.h:50,
                 from /usr/lib64/R/library/Rcpp/include/Rcpp.h:27,
                 from commR.h:27,
                 from AnnoProb.cpp:12:
/usr/include/c++/4.8.2/streambuf:802:7: error: ‘std::basic_streambuf<_CharT, _Traits>::basic_streambuf(const std::basic_streambuf<_CharT, _Traits>&) [with _CharT = char; _Traits = std::char_traits<char>]’ is private
       basic_streambuf(const basic_streambuf& __sb)
       ^
In file included from /usr/lib64/R/library/RcppEigen/include/unsupported/Eigen/SparseExtra:22:0,
                 from /usr/lib64/R/library/RcppEigen/include/RcppEigenForward.h:40,
                 from /usr/lib64/R/library/RcppEigen/include/RcppEigen.h:25,
                 from commR.h:28,
                 from AnnoProb.cpp:12:
/usr/include/c++/4.8.2/fstream:72:11: error: within this context
     class basic_filebuf : public basic_streambuf<_CharT, _Traits>
           ^
In file included from /usr/include/c++/4.8.2/utility:70:0,
                 from /usr/include/c++/4.8.2/unordered_map:38,
                 from /usr/lib64/R/library/Rcpp/include/Rcpp/platform/compiler.h:153,
                 from /usr/lib64/R/library/Rcpp/include/Rcpp/r/headers.h:62,
                 from /usr/lib64/R/library/Rcpp/include/RcppCommon.h:30,
                 from /usr/lib64/R/library/Rcpp/include/Rcpp.h:27,
                 from commR.h:27,
                 from AnnoProb.cpp:12:
/usr/include/c++/4.8.2/bits/stl_pair.h: In instantiation of ‘constexpr std::pair<_T1, _T2>::pair(_U1&&, const _T2&) [with _U1 = std::basic_string<char>; <template-parameter-2-2> = void; _T1 = const std::basic_string<char>; _T2 = std::basic_ofstream<char>]’:
/usr/include/c++/4.8.2/bits/stl_tree.h:140:49:   required from ‘std::_Rb_tree_node<_Val>::_Rb_tree_node(_Args&& ...) [with _Args = {std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_ofstream<char, std::char_traits<char> >}; _Val = std::pair<const std::basic_string<char>, std::basic_ofstream<char> >]’
/usr/include/c++/4.8.2/ext/new_allocator.h:120:4:   required from ‘void __gnu_cxx::new_allocator<_Tp>::construct(_Up*, _Args&& ...) [with _Up = std::_Rb_tree_node<std::pair<const std::basic_string<char>, std::basic_ofstream<char> > >; _Args = {std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_ofstream<char, std::char_traits<char> >}; _Tp = std::_Rb_tree_node<std::pair<const std::basic_string<char>, std::basic_ofstream<char> > >]’
/usr/include/c++/4.8.2/bits/alloc_traits.h:254:4:   required from ‘static typename std::enable_if<std::allocator_traits<_Alloc>::__construct_helper<_Tp, _Args>::value, void>::type std::allocator_traits<_Alloc>::_S_construct(_Alloc&, _Tp*, _Args&& ...) [with _Tp = std::_Rb_tree_node<std::pair<const std::basic_string<char>, std::basic_ofstream<char> > >; _Args = {std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_ofstream<char, std::char_traits<char> >}; _Alloc = std::allocator<std::_Rb_tree_node<std::pair<const std::basic_string<char>, std::basic_ofstream<char> > > >; typename std::enable_if<std::allocator_traits<_Alloc>::__construct_helper<_Tp, _Args>::value, void>::type = void]’
/usr/include/c++/4.8.2/bits/alloc_traits.h:393:57:   required from ‘static decltype (_S_construct(__a, __p, (forward<_Args>)(std::allocator_traits::construct::__args)...)) std::allocator_traits<_Alloc>::construct(_Alloc&, _Tp*, _Args&& ...) [with _Tp = std::_Rb_tree_node<std::pair<const std::basic_string<char>, std::basic_ofstream<char> > >; _Args = {std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_ofstream<char, std::char_traits<char> >}; _Alloc = std::allocator<std::_Rb_tree_node<std::pair<const std::basic_string<char>, std::basic_ofstream<char> > > >; decltype (_S_construct(__a, __p, (forward<_Args>)(std::allocator_traits::construct::__args)...)) = <type error>]’
/usr/include/c++/4.8.2/bits/stl_tree.h:408:36:   required from ‘std::_Rb_tree_node<_Val>* std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_M_create_node(_Args&& ...) [with _Args = {std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_ofstream<char, std::char_traits<char> >}; _Key = std::basic_string<char>; _Val = std::pair<const std::basic_string<char>, std::basic_ofstream<char> >; _KeyOfValue = std::_Select1st<std::pair<const std::basic_string<char>, std::basic_ofstream<char> > >; _Compare = std::less<std::basic_string<char> >; _Alloc = std::allocator<std::pair<const std::basic_string<char>, std::basic_ofstream<char> > >; std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_Link_type = std::_Rb_tree_node<std::pair<const std::basic_string<char>, std::basic_ofstream<char> > >*]’
/usr/include/c++/4.8.2/bits/stl_tree.h:1622:64:   required from ‘std::pair<std::_Rb_tree_iterator<_Val>, bool> std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_M_emplace_unique(_Args&& ...) [with _Args = {std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_ofstream<char, std::char_traits<char> >}; _Key = std::basic_string<char>; _Val = std::pair<const std::basic_string<char>, std::basic_ofstream<char> >; _KeyOfValue = std::_Select1st<std::pair<const std::basic_string<char>, std::basic_ofstream<char> > >; _Compare = std::less<std::basic_string<char> >; _Alloc = std::allocator<std::pair<const std::basic_string<char>, std::basic_ofstream<char> > >]’
/usr/include/c++/4.8.2/bits/stl_map.h:541:64:   required from ‘std::pair<typename std::_Rb_tree<_Key, std::pair<const _Key, _Tp>, std::_Select1st<std::pair<const _Key, _Tp> >, _Compare, typename _Alloc::rebind<std::pair<const _Key, _Tp> >::other>::iterator, bool> std::map<_Key, _Tp, _Compare, _Alloc>::emplace(_Args&& ...) [with _Args = {std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_ofstream<char, std::char_traits<char> >}; _Key = std::basic_string<char>; _Tp = std::basic_ofstream<char>; _Compare = std::less<std::basic_string<char> >; _Alloc = std::allocator<std::pair<const std::basic_string<char>, std::basic_ofstream<char> > >; typename std::_Rb_tree<_Key, std::pair<const _Key, _Tp>, std::_Select1st<std::pair<const _Key, _Tp> >, _Compare, typename _Alloc::rebind<std::pair<const _Key, _Tp> >::other>::iterator = std::_Rb_tree_iterator<std::pair<const std::basic_string<char>, std::basic_ofstream<char> > >]’
AnnoProb.cpp:93:105:   required from here
/usr/include/c++/4.8.2/bits/stl_pair.h:134:45: error: use of deleted function ‘std::basic_ofstream<char>::basic_ofstream(const std::basic_ofstream<char>&)’
  : first(std::forward<_U1>(__x)), second(__y) { }
                                             ^
make: *** [AnnoProb.o] Error 1
ERROR: compilation failed for package ‘SBayesRC’
* removing ‘/usr/lib64/R/library/SBayesRC’
Warning message:
In install.packages("https://github.com/zhilizheng/SBayesRC/releases/download/v0.2.0/SBayesRC_0.2.0.tar.gz",  :
  installation of package ‘/users/tmp/RtmpiNDJwl/downloaded_packages/SBayesRC_0.2.0.tar.gz’ had non-zero exit status

**Comment by zhilizheng** [comment]
Hi @irgp2019 ,

Thanks for the report.  This may be an issue from Rcpp package ( I documented this).   When error happened,  we only include the header, and compiler look into Rcpp header.    I also install a fresh CentOS7 (CentOS7.9, R 3.6.0, gcc4.8.5), however, I run into the problem when install the RcppEigen which depends on Rcpp package.  I tried mutliple ways, the **easiest way to correct** it is using anaconda, it works even without sudo permission: 

```bash
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh  
sh Miniconda3-latest-Linux-x86_64.sh -b  # remove the -b if you'd like to customize the locations. 
conda activate    # make sure the "base" is in your prompt; You can also create enviroment. 
conda install r-essentials

R
### run in R
# Run in R to install dependencies
install.packages(c("Rcpp", "data.table", "stringi", "BH",  "RcppEigen"))
# Install SBayesRC package
# Almost all warnings comes from RcppEigen Package,  sorry for that... 
install.packages("https://github.com/zhilizheng/SBayesRC/releases/download/v0.2.0/SBayesRC_0.2.0.tar.gz",
                 repos=NULL, type="source")
quite()
### return to bash
# each time you need run SBayesRC:
conda activate 
# then copy my example script
# If you'd like to run in computation nodes (jobs), anaconda would have problem even you have "conda activate"
RSCRIPT_PATH=$(which Rscript)
# replace the "Rscript" in the script to "$RSCRIPT_PATH"
```

Let me know if this solve your problem or not. 

Regards,
Zhili

**Comment by zhilizheng** [comment]
Hi @irgp2019 ,

We now provide the Docker image for easy running without installation.   The image address: zhiliz/sbayesrc

You can use the image in local cluster by apptainer/singluar, which is very common in HPC.    You can also use the image on cloud directly (UKB RAP, AWS, GCP).  

Example to run on local cluster by apptainer: 
```
# run clean and impute
# ldm is the ld_folder in my document;  test.ma is the summary data;  annota.txt is the annotation file
apptainer run docker://zhiliz/sbayesrc --ldm-eigen ldm --gwas-summary test.ma --impute-summary --out test --thread 4
# run SBayesRC
apptainer run docker://zhiliz/sbayesrc --ldm-eigen ldm --gwas-summary test.imputed.ma --sbayes RC --annot annot.txt --out test --thread 4
```

Hope it makes the running easier. 

Regards,
Zhili
