### ISSUE TITLE
Core dumped, final step

### ISSUE THREAD

**Issue by vwarrier** [zhilizheng/SBayesRC#7]
Hello,

Thank you for this interesting method. I've been trying this using both the executable on the GCTB webpage and the code over here. I'm able to run the programme up until imputation, but have been running into issues after that neither using the code nor the executable. I can run SBayesR, but not SBayesRC. 

I was wondering if you could please let me know what the potential issue is? The log is attached.
[depression_impute_sbrc.log](https://github.com/zhilizheng/SBayesRC/files/11563170/depression_impute_sbrc.log)

Thanks,
Varun

**Comment by zhilizheng** [comment]
Hi @vwarrier 

Thanks for the report.  It looks like some files in the LD folder have problem (the error means:  read the number of markers error).    

Could you send me the output of:  
ls -ltr ~/GCTA/SBayesRC/ukbEUR_Imputed/
md5sum ~/GCTA/SBayesRC/ukbEUR_Imputed/block591.eigen.bin
md5sum ~/GCTA/SBayesRC/ukbEUR_Imputed/block1.eigen.bin
md5sum ~/GCTA/SBayesRC/ukbEUR_Imputed/snp.info
md5sum ~/GCTA/SBayesRC/ukbEUR_Imputed/ldm.info

Thanks. 

Regards,
Zhili

**Comment by vwarrier** [comment]
Dear Zhili,

Thanks! Please find the information you requested below and attached.


ls -ltr ~/GCTA/SBayesRC/ukbEUR_Imputed/? - attached


md5sum ~/GCTA/SBayesRC/ukbEUR_Imputed/block591.eigen.bin: b1abcf77a9f37223e096d97c2eeda8dd
md5sum ~/GCTA/SBayesRC/ukbEUR_Imputed/block1.eigen.bin: 8dc6b752c66ccb1e81488419b01ffb79
md5sum ~/GCTA/SBayesRC/ukbEUR_Imputed/snp.info: 6b31ce56797d2b65280b7b0733b93f30
md5sum ~/GCTA/SBayesRC/ukbEUR_Imputed/ldm.info : be171ed0a7adf6169288d7a362d6bbd9


Thank you,
Varun




I do not expect a response outside your office hours

________________________________

**Comment by zhilizheng** [comment]
Hi @vwarrier ,

Many thanks for the information.  I checked the files should be all fine.  Strangely,  I run without any problem on my side.  I plan to simulate exactly the same enviroment of your machine.  

Beside, I noticed , you run on the head node,  do you have some restrictions to run on head node?  I don't whether submit the job would solve the problem or not. 

Could you send me the information of your machine for my simulation?   (such as Linux version, R version).  If you don't know, just run the below code, and share me the sendzz.txt

echo "=====R configure" &> sendzz.txt
Rscript -e "sessionInfo()" &>> sendzz.txt

echo "=====ld version" &>> sendzz.txt
ldd --version &>>  sendzz.txt

echo "===== Linux" &>> sendzz.txt
cat /etc/*release* &>> sendzz.txt

echo "=====Kernel" &>> sendzz.txt
uname -a &>> sendzz.txt

echo "=====CPU info" &>> sendzz.txt
cat "/proc/cpuinfo" &>> sendzz.txt

echo "=====lscpu" &>> sendzz.txt
lscpu &>> sendzz.txt

Thanks.

Regards,
Zhili

**Comment by zhilizheng** [comment]
Hi @vwarrier 

I find my previous code in the message would expose your machine's full host name, which may be not good for your security.  Could you refer to the github issue page,  copy and run the newest code?  I removed the part that may expose your privacy. 

Thanks for your help with the debug.

Regards,
Zhili
