### ISSUE TITLE
# SBayesRC: main function for SBayesRC

### ISSUE THREAD

**Issue by NiranOkewole** [zhilizheng/SBayesRC#8]
Hi,
I was also able to get through the imputation but had an error at this step: 

Rscript -e "SBayesRC::sbayesrc(mafile='${out_prefix}_imp.ma', LDdir='$ld_folder', outPrefix='${out_prefix}_sbrc', annot='$annot', log2file=TRUE)"

Error in SBayesRC::sbayesrc(mafile = "./asdtest_imp.ma", LDdir = "ukbEUR_Imputed",  :
  Warning, the best parameter is the minimumn threshold, we suggest to expand the tuning grid by specify lower tuning value, e.g. tuneStep=c(0.995, 0.9, 0.8, 0.7, 0.6)
Execution halted

Not entirely sure how or where to add the tuneStep.

**Comment by NiranOkewole** [comment]
Hi @zhilizheng 

That worked, thanks. I am on the final (plink) step but I get an error when I run: 

plink2 --bfile $YOUR_GENO_PLINK --score ${out_prefix}_sbrc.txt 1 2 3 header sum center --threads $OMP_NUM_THREADS --out MYPRS

Error: Invalid --score argument 'sum'.
For more info, try "plink2 --help <flag name>" or "plink2 --help | more". 

Plink2 doesn't have a 'sum' flag. Should this be replaced with something else? 

Best,
Niran

**Comment by zhilizheng** [comment]
Hi @NiranOkewole ,

Thanks for your report about the PRS from PLINK, indeed,  this is the command line for plink1.9.  Sorry for the confusion.  I will change the text. 

Regards,
Zhili

**Comment by NiranOkewole** [comment]
Hi @zhilizheng 
Yes I deleted the query after running the code/script with plink 1.9, but thanks for addressing it all the same.

I am currently trying to understand and maximise the output, especially the functional annotations. Looking forward to your publication.

Best regards,
Niran
